### ISSUE TITLE
Error "Unkown type of a PPI actor" with AnonymousModification

### ISSUE THREAD

**Issue by slegare2** [Kappa-Dev/KAMI#17]
With the following script:

```
from kami.entities import (Gene, Region, Site, Residue, State, RegionActor,
                           SiteActor)
from kami.interactions import (Binding, Unbinding, Modification,
                               TransModification, AutoModification,
                               AnonymousModification)
from kami.hierarchy import (KamiHierarchy)
from regraph import print_graph

inter = AnonymousModification(
    substrate=Gene(uniprotid="P06239",
                   hgnc_symbol="LCK"),
    target=Residue(aa="Y", loc=394,
                   state=State("phosphorylation", True)),
    value=False,
    rate=0.01
)

print(inter)
hierarchy = KamiHierarchy()
hierarchy.add_interaction(inter, anatomize=False)

print("printing nugget_1")
print_graph(hierarchy.graph['nugget_1'])
```
i get this error:

```
AnonymousModification:
	Substrate: P06239
	Mod target: Y394
	Value: False
	Rate: 0.01

Traceback (most recent call last):
  File "anonymousmod.py", line 21, in <module>
    hierarchy.add_interaction(inter, anatomize=False)
  File "/home/slegare/ENS/venv_meta_update/lib/python3.6/site-packages/kami-1.2-py3.6.egg/kami/hierarchy.py", line 840, in add_interaction
    nugget, nugget_type = generator.generate(interaction)
  File "/home/slegare/ENS/venv_meta_update/lib/python3.6/site-packages/kami-1.2-py3.6.egg/kami/aggregation/generators.py", line 456, in generate
    nugget, mod.enzyme)
  File "/home/slegare/ENS/venv_meta_update/lib/python3.6/site-packages/kami-1.2-py3.6.egg/kami/aggregation/generators.py", line 399, in _generate_actor
    "Unkown type of a PPI actor: '%s'" % type(actor)
kami.exceptions.NuggetGenerationError: Unkown type of a PPI actor: '<class 'NoneType'>'
```

**Comment by eugeniashurko** [comment]
Fixed in the previous commit https://github.com/Kappa-Dev/KAMI/commit/4841e2d9dbdda57e58b82f0e2ca5f92882bbeb31
